name: Ci⚠️：tosasitillKernelAutoBuild(NO TESTED)



on:
  workflow_dispatch:
    inputs:
      KERNEL_VER:
        description: 'Kernel Version/内核版本(仅数字)'
        required: true
        default: '1.6-ksu'

jobs:
  Ci-tosasitillKernelAutoBuild:
    runs-on: ubuntu-20.04
    steps:
      - name: 获取源代码
        uses: actions/checkout@main
        with: 
          path: tosasitillKernel_polaris
          
      - name: Building
        run: |
          wget https://github.com/tosasitill/tosasitillKernel_polaris/blob/ONLINE/setup.sh
          ls
          sudo chmod +x setup.sh
          sudo bash ${{ github.workspace }}/setup.sh
          
      - name: 创建 INFO 文件
        run: |
          echo "内核编译设备: Xiaomi MIX 2S
          代码感谢: SakuraNotestupid/tosasitill
          编译序号: ${{ github.run_number }}
          KernelSU For Xiaomi MIX 2S
          编译日期:$date
          编译耗时: $((total_time / 60)) 分钟 $((total_time % 60)) 秒
          Copyright © 2023 tosasitill 0202 & 0227 Made with love" >> INFO.txt
          
      - name: 上传 Kernel
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: ~/tosasitillKernel-Ci-V${{ github.event.inputs.KERNEL_VER }}.zip
          name: "Xiaomi_MIX2S_KernelSU"
          tag: " ${{ github.run_number }}_Xiaomi_MIX2S_KernelSU"
          bodyFile: "~/android_kernel_xiaomi_sdm845_LineageOS/INFO.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
